#pragma once

#define INCLUDE_TEX_Envmap
//#define INCLUDE_TEX_Plasma
#define INCLUDE_TEX_Map
#define INCLUDE_TEX_Blur
#define INCLUDE_TEX_DirBlur
#define INCLUDE_TEX_Text
#define INCLUDE_TEX_SubPlasma
#define INCLUDE_TEX_FractalPlasma
#define INCLUDE_TEX_Colorize
#define INCLUDE_TEX_Shade
#define INCLUDE_TEX_Brightness
#define INCLUDE_TEX_Copy
#define INCLUDE_TEX_Cells
#define INCLUDE_TEX_Twirl
//#define INCLUDE_TEX_SineDist
//#define INCLUDE_TEX_Mix
#define INCLUDE_TEX_MixMap
//#define INCLUDE_TEX_Scale
//#define INCLUDE_TEX_SineColor
//#define INCLUDE_TEX_Max
//#define INCLUDE_TEX_HSV
//#define INCLUDE_TEX_Emboss
#define INCLUDE_TEX_Invert
#define INCLUDE_TEX_Glass
//#define INCLUDE_TEX_Pixelize
#define INCLUDE_TEX_Offset
#define INCLUDE_TEX_Crystalize
//#define INCLUDE_TEX_Rectangle
#define INCLUDE_TEX_Circle
#define INCLUDE_TEX_Contrast
#define INCLUDE_TEX_MakeMaterial
#define INCLUDE_TEX_Gradient
#define INCLUDE_TEX_Rotozoom
#define INCLUDE_TEX_ChamferRectangle
//#define INCLUDE_TEX_Dots
#define INCLUDE_TEX_Jpeg
//#define INCLUDE_TEX_FractalPlasmaOld


#define INCLUDE_OBJ_BOX
#define INCLUDE_OBJ_SPHERE
#define INCLUDE_OBJ_CYLINDER
#define INCLUDE_OBJ_CONE
#define INCLUDE_OBJ_PLANE
#define INCLUDE_OBJ_ARC
//#define INCLUDE_OBJ_LINE
#define INCLUDE_OBJ_LOFT
//#define INCLUDE_OBJ_ICOSAEDER
//#define INCLUDE_OBJ_DODECAEDER
//#define INCLUDE_OBJ_CIRCLE
#define INCLUDE_OBJ_CLONE
//#define INCLUDE_OBJ_STORED
//#define INCLUDE_OBJ_FUR
//#define INCLUDE_OBJ_SUPERSHAPE

#define INCLUDE_MESHSMOOTH

#define INCLUDE_OBJ_MAPXFORM
#define INCLUDE_OBJ_LINEARSMOOTH
#define INCLUDE_OBJ_BUTTERFLYSMOOTH
#define INCLUDE_OBJ_MESHBLUR


#define INCLUDE_PARTICLE_ENGINE

//#define INCLUDE_WRL_DUMMY
#define INCLUDE_WRL_SCENE
#define INCLUDE_WRL_SUBSCENE
#define INCLUDE_WRL_SPHEREEMITTER
#define INCLUDE_WRL_CUBEEMITTER
//#define INCLUDE_WRL_CYLINDEREMITTER
//#define INCLUDE_WRL_PLANEDEFLECTOR
//#define INCLUDE_WRL_SPHEREDEFLECTOR
#define INCLUDE_WRL_GRAVITY


#define INCLUDE_EVENT_NOEFFECT
#define INCLUDE_EVENT_2DLAYER
#define INCLUDE_EVENT_PARTICLECALC
#define INCLUDE_EVENT_CLEAR
#define INCLUDE_EVENT_RENDERTOTEXTURE
#define INCLUDE_EVENT_FEEDBACK
#define INCLUDE_EVENT_BLUR
#define INCLUDE_EVENT_3DSCENE
//#define INCLUDE_EVENT_PARTICLERESET
#define INCLUDE_EVENT_CONTRAST
//#define INCLUDE_EVENT_FUNKENDSCROLL
//#define INCLUDE_EVENT_CRYSTALIZE
#define INCLUDE_EVENT_GRIDFILLER
//#define INCLUDE_EVENT_CAVE
#define INCLUDE_EVENT_CAMSHAKE
#define INCLUDE_EVENT_MRCEFFECT
#define INCLUDE_EVENT_FEEDBACK2
